layout: app
title: Fahrenheit 52
base_url: https://f52.charlieharrington.com
podcast_category: Fiction
podcast_language: en-us
podcast_subtitle: One short story, every week.
podcast_author: Charlie Harrington
podcast_summary: One short story for every week in 2022, with the hopes that one of them might actually be good.
podcast_explicit: 'no'
podcast_email: f52@whatrocks.org
podcast_img_url: 'https://whatrocks.github.io/fahrenheit-52/static/f52c.jpg'